apiVersion: v1
kind: Secret
metadata:
  name: demo-secrets
  labels:
    app: demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  database-url: amRiYzptYXJpYWRiOi8vbWFyaWFkYi1zZXJ2aWNlOjMzMDYvY2FyZGI=
  database-username: Y2FydXNlcg==
  database-password: bWxqUjFJa0QyMUNzQ0NaTUQwNjVvTVBvRw==
  jwt-secret: ODZTdEVJUWNMYWQ5NjdNbWRiRzFsaDdNVFE0OVU3bUFTcWlLeTE3SERsc1hGMEt1ZldZTHQzbm8zT1VaUQ0KRm1sZXZGU3VLQVVwRlExTmc5ckE=
