# Kubernetes Deployment Configuration
# ArgoCD Compatible Configuration
# Last deployed: 2025-08-12T00:00:00Z

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
    version: v1
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/component: web-service
    app.kubernetes.io/part-of: demo-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
        version: v1
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ["sh","-c"]
        args:
          - |
            for i in $(seq 1 120); do
              nc -z mariadb-service.$NAMESPACE.svc 3306 && exit 0
              echo "waiting for mariadb..."
              sleep 2
            done
            echo "timeout waiting for mariadb" >&2
            exit 1
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      containers:
      - name: demo-app
        image: ghcr.io/max2535/demo:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: demo-secrets
              key: database-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: demo-secrets
              key: database-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secrets
              key: database-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: demo-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  labels:
    app: demo-app
spec:
  selector:
    app: demo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - demo.example.com
    secretName: demo-app-tls
  rules:
  - host: demo.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-app-service
            port:
              number: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: demo-secrets
type: Opaque
stringData:
  database-url: jdbc:mariadb://mariadb-service:3306/cardb
  database-username: caruser
  database-password: change-this-password
  jwt-secret: change-this-to-a-256-bit-secret-key

---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-creds
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJUVmhZTWpVek5UcG5hRE5vWDJoMFltZGZkRzlyWlc0PSIKCQl9Cgl9Cn0=
