apiVersion: v1
kind: Secret
metadata:
  name: ghcr-creds
  labels:
    app: demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiTWF4MjUzNSIsInBhc3N3b3JkIjoiZGVtb190b2tlbl9wbGFjZWhvbGRlciIsImF1dGgiOiJUV0Y0TWpVek5UcGtaVzF2WDNSdmEyVnVYM0JzWVdObGFHOXNaR1Z5In19fQ==
