apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  labels:
    app: mariadb
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  root-password: QXRodWh6VHJZaEV1dzNDRlhKbjlyTktXdQ==
  user-password: bWxqUjFJa0QyMUNzQ0NaTUQwNjVvTVBvRw==
