apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc-standard
  labels:
    app: mariadb
    app.kubernetes.io/name: mariadb-storage
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: demo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
