apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-scripts
  labels:
    app: mariadb
data:
  init.sql: |
    -- Create the cardb database if it doesn't exist
    CREATE DATABASE IF NOT EXISTS cardb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    
    -- Use the cardb database
    USE cardb;
    
    -- Create owners table
    CREATE TABLE IF NOT EXISTS owners (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        phone VARCHAR(20),
        address TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB;
    
    -- Create cars table
    CREATE TABLE IF NOT EXISTS cars (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        brand VARCHAR(100) NOT NULL,
        model VARCHAR(100) NOT NULL,
        year INT NOT NULL,
        color VARCHAR(50),
        license_plate VARCHAR(20) UNIQUE NOT NULL,
        owner_id BIGINT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE SET NULL
    ) ENGINE=InnoDB;
    
    -- Create users table for authentication
    CREATE TABLE IF NOT EXISTS users (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        role VARCHAR(20) DEFAULT 'USER',
        enabled BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB;
    
    -- Insert sample data
    INSERT IGNORE INTO owners (name, email, phone, address) VALUES 
    ('John Doe', 'john.doe@example.com', '+1234567890', '123 Main St, City, Country'),
    ('Jane Smith', 'jane.smith@example.com', '+1987654321', '456 Oak Ave, Town, Country'),
    ('Bob Johnson', 'bob.johnson@example.com', '+1122334455', '789 Pine Rd, Village, Country');
    
    INSERT IGNORE INTO cars (brand, model, year, color, license_plate, owner_id) VALUES 
    ('Toyota', 'Camry', 2020, 'Blue', 'ABC123', 1),
    ('Honda', 'Civic', 2019, 'Red', 'XYZ789', 2),
    ('Ford', 'Focus', 2021, 'White', 'DEF456', 1),
    ('Nissan', 'Altima', 2018, 'Black', 'GHI789', 3);
    
    -- Insert a default admin user (password: admin123 - should be changed in production)
    INSERT IGNORE INTO users (username, password, email, role) VALUES 
    ('admin', '$2a$10$9Q5z5z5z5z5z5z5z5z5z5e5z5z5z5z5z5z5z5z5z5z5z5z5z5z5z5', 'admin@example.com', 'ADMIN');
    
    -- Grant permissions to caruser
    GRANT SELECT, INSERT, UPDATE, DELETE ON cardb.* TO 'caruser'@'%';
    FLUSH PRIVILEGES;
    
    -- Show tables for verification
    SHOW TABLES;
