apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  labels:
    app: mariadb
type: Opaque
data:
  # These are base64 encoded values
  # root-password: Base64 encoded random password (generate with: echo -n "password" | base64)
  # user-password: Base64 encoded random password
  # Note: In production, these should be generated securely
  root-password: bXlzZWNyZXRyb290cGFzcw==  # mysecretrootpass
  user-password: bXlzZWNyZXR1c2VycGFzcw==  # mysecretuserpass
