# MariaDB Database Deployment
# ArgoCD Compatible Configuration

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: demo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.3
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: root-password
        - name: MYSQL_DATABASE
          value: cardb
        - name: MYSQL_USER
          value: caruser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: user-password
        # Add configuration to handle Aria engine properly
        - name: MYSQL_INITDB_SKIP_TZINFO
          value: "1"
        args:
          - --character-set-server=utf8mb4
          - --collation-server=utf8mb4_unicode_ci
          - --skip-character-set-client-handshake
          - --aria-log-file-size=64M
          - --aria-log-purge-type=immediate
          - --aria-max-sort-file-size=2G
          - --innodb-flush-method=fsync
          - --innodb-use-native-aio=0
          - --sync-binlog=0
        ports:
        - containerPort: 3306
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  mysqladmin -u root -p$MYSQL_ROOT_PASSWORD shutdown || true
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 3
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc-standard
      - name: init-scripts
        configMap:
          name: mariadb-init-scripts

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mariadb
spec:
  selector:
    app: mariadb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP

# PVC has been moved to a separate file (mariadb-pvc-standard.yml)
# This allows for easier replacement when storage requirements change
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mariadb-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: standard

---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
stringData:
  root-password: change-this-root-password
  user-password: change-this-user-password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-scripts
data:
  init.sql: |
    -- Create tables
    CREATE TABLE IF NOT EXISTS owners (
      id INT AUTO_INCREMENT PRIMARY KEY,
      first_name VARCHAR(100) NOT NULL,
      last_name VARCHAR(100) NOT NULL
    );
    
    CREATE TABLE IF NOT EXISTS cars (
      id INT AUTO_INCREMENT PRIMARY KEY,
      brand VARCHAR(100) NOT NULL,
      model VARCHAR(100) NOT NULL,
      year INT NOT NULL,
      owner_id INT,
      FOREIGN KEY (owner_id) REFERENCES owners(id)
    );
    
    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      username VARCHAR(50) NOT NULL UNIQUE,
      password VARCHAR(100) NOT NULL,
      roles VARCHAR(100) NOT NULL
    );

    -- Initial data for the application
    INSERT INTO owners (first_name, last_name) VALUES 
    ('John', 'Doe'),
    ('Jane', 'Smith'),
    ('Bob', 'Johnson');

    INSERT INTO cars (brand, model, year, owner_id) VALUES 
    ('Toyota', 'Camry', 2022, 1),
    ('Honda', 'Civic', 2021, 1),
    ('Ford', 'Mustang', 2023, 2),
    ('BMW', '3 Series', 2022, 3);

    -- Create admin user
    INSERT INTO users (username, password, roles) VALUES 
    ('admin', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'ADMIN');
    
    -- Password is 'password' - change this in production!
